language: android

bundler_args: --retry 3

android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - sys-img-x86-android-wear-20
    - android-21

before_install:
  - android list sdk --no-ui --all --extended
  - echo "no"|android create avd --force -n Phone --target "android-19" --abi armeabi-v7a
  #- sleep 10
  #- echo "no"|android create avd --force -n WatchRound --target "android-20" --device "Android Wear Round" --skin AndroidWearRound --abi android-wear/armeabi-v7a
  #- sleep 10
  - emulator -avd Phone -no-skin -no-audio -no-window &
  #- sleep 15
  #- emulator -avd WatchRound -verbose -no-skin -no-audio -no-window &
  - sleep 15
  - ./gradlew app:assembleDebugTest
  - timeout 430 android-wait-for-emulator | xargs echo
  - adb devices
script:
  - ./gradlew app:connectedAndroidTest
  - cat app/build/outputs/reports/androidTests/connected/index.html
  - adb devices
