language: android

bundler_args: --retry 3

android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - sys-img-x86-android-wear-20
    - android-21

before_install:
  - android list sdk --no-ui --all --extended
  - echo "no"|android create avd --force -n Phone --target "android-19" --abi armeabi-v7a
  - echo "no"|android create avd --force -n WatchRound --target "android-20" --device "Android Wear Round" --skin AndroidWearRound --abi android-wear/armeabi-v7a
  - emulator -avd Phone -no-skin -no-audio -no-window &
  - emulator -avd WatchRound -verbose -no-skin -no-audio -no-window &
  - sleep 30
  - ./gradlew app:assembleDebugTest
  - timeout 590 android-wait-for-emulator 2> /dev/null
  - adb devices
script:
  - jobs
  - adb devices
  - ./gradlew app:connectedAndroidTest
  - adb devices
